<!-- filepath: /Users/isaaccandari/CS/Work/Course-Scheduler/major_options.php -->
<option value="majors/ACCT.json">Accounting</option>
<option value="majors/ANTH.json">Anthropology</option>
<option value="majors/MATHPURE.json">Applied Mathematics</option>
<option value="majors/ART.json">Art</option>
<option value="majors/BIOL.json">Biology</option>
<option value="majors/BUSME.json">Business Management</option>
<option value="majors/BUSMF.json">Business Marketing</option>
<option value="majors/BUSMM.json">Business Marketing Management</option>
<option value="majors/BUSMO.json">Business Operations</option>
<option value="majors/BUSMS.json">Business Systems</option>
<option value="majors/COMM.json">Communications</option>
<option value="majors/CS.json">Computer Science</option>
<option value="majors/ELEME.json">Elementary Education</option>
<option value="majors/ENGL.json">English</option>
<option value="majors/ENGLEDU.json">English Education</option>
<option value="majors/HAWNSTU.json">Hawaiian Studies</option>
<option value="majors/HHSM.json">Health and Human Science</option>
<option value="majors/HIST.json">History</option>
<option value="majors/HISTEDU.json">History Education</option>
<option value="majors/HTM.json">Hotel and Tourism Management</option>
<option value="majors/IT.json">Information Technology</option>
<option value="majors/PEACE.json">Peace Studies</option>
<option value="majors/MATHE.json">Math Education</option>
<option value="majors/MATHB.json">Mathematics - Biology</option>
<option value="majors/MATHCS.json">Mathematics - Computer Science</option>
<option value="majors/MATHP.json">Mathematics - Physics</option>
<option value="majors/MATHENG.json">Mathematics Engineering</option>
<option value="majors/MATHS.json">Mathematics - Statistics</option>
<option value="majors/MUSIC.json">Music</option>
<option value="majors/PAS.json">Pacific Studies</option>
<option value="majors/POSC.json">Political Science</option>
<option value="majors/PSYC.json">Psychology</option>
<option value="majors/MATHPE.json">Pure Mathematics</option>
<option value="majors/SCIEDU.json">Science Education</option>
<option value="majors/SOSCI.json">Sociology</option>
<option value="majors/SOCWM.json">Social Work</option>
<option value="majors/TESOL.json">TESOL</option>
<option value="majors/TESOLEDU.json">TESOL Education</option>
<option value="majors/VA.json">Visual Arts</option>
<option value="majors/VAFA.json">Visual Arts - Fine Arts</option>
<!-- Add remaining options as needed -->